apiVersion: v1
kind: Namespace
metadata:
  name: jsde

---
apiVersion: v1
kind: Service
metadata:
  name: jsde-app
  namespace: jsde
spec:
  selector:
    app: jsde-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsde-app
  namespace: jsde
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsde-app
  template:
    metadata:
      labels:
        app: jsde-app
    spec:
      containers:
      - name: jsde-app
        image: ghcr.io/jannik-schroeder/jsde-me:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jsde-app
  namespace: jsde
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jsde.me`)
      kind: Rule
      services:
        - name: jsde-app
          port: 3000
  tls:
    secretName: jsde-scpx-de-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jsde-scpx-de
  namespace: jsde
spec:
  secretName: jsde-scpx-de-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - jsde.me
