name: Trigger Git Pull on Server

on:
  push:
    branches:
      - main # oder den Namen des Zweiges, den du überwachen möchtest, z.B. 'master' 

jobs:
  trigger-pull:
    runs-on: ubuntu-latest

    steps:
    - name: Send request to server to trigger git pull
      run: |
        curl -k -X POST https://api.arlinx.de/execute -H "Content-Type: application/json" -H "x-api-key: ${{ secrets.API_TOKEN }}"
